version: '3'

services:
  hopetail-mysql:
    container_name: hopetail-mysql
    image: mysql:9.2.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: hopetail-db
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
