spring:
  application:
    name: hopetail-be

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: on
    properties:
      hibernate:
        format_sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/hopetail-db?autoReconnect=true
    username: user
    password: '1234'

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    display-request-duration: true