spring:
  application:
    name: hopetail-be

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/hopetail-db?autoReconnect=true
    username: minsung
    password: minsung1234

  data:
    redis:
      host: localhost
      port: 6379
      password:

# 레디스 설치 없이 이용 시 docker로 실행
# docker run -d --name redis -p 6379:6379 redis


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
    display-request-duration: true

jwt:
  header: Authorization
  secret: dGhpcyBpcyBteSBoaWRkZW4gand0IHNlY3JldGUga2V5LCB3aGF0IGlzIHlvdXIgand0IHNlY3JldGUga2V5Pw==
  access-token-validity-in-seconds: 3600
