spring:
  application:
    name: hopetail-be

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
    properties:
      hibernate:
        format_sql: true
    database: mysql
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    display-request-duration: true

